### ISSUE TITLE
./new_dataset.npz

### ISSUE THREAD

**Issue by MorphSeur** [markub3327/HAR-Transformer#2]
Hi,

May I know what is inside ./new_dataset.npz?
It seems that in https://www.kaggle.com/datasets/niloy333/kuhar, I can't find signals and labels that are specified in:
       f = np.load('./new_dataset.npz')
       signals = f['signals']
       labels = f['labels']

Thanks in advance,

**Comment by MorphSeur** [comment]
Hello,

May I know which version of Tensorflow you used?

Thank you,

**Comment by markub3327** [comment]
Hello,

   the version was 2.9.

`new_dataset.npz` contains samples after data augmentation of original kuHAR dataset. The data augmentation process logicaly combines the pairs of 2 different activities into one windows. It represents the transition from one activity to another one. And drops the damaged samples from the original kuHAR dataset - bad measurements.  

`new_dataset.npz` must contains `signals` and `labels` because is saving with
`np.savez_compressed("new_dataset", signals=final_signals, labels=final_labels)` !!!

Thanks.

**Comment by MorphSeur** [comment]
Thanks a lot for the clarifications.
